apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-microservice-demo-application
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: release/manifests
    repoURL: https://github.com/AmrFawzymoh/microservices-private-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
